# Welcome to Jekyll!
encoding: utf-8
permalink: /:path/:basename

# Site settings
title: ARRRmada Directory - ARRR (Pirate Chain) accepted here
keywords: cryptocurrency, privacy, pirate chain, arrr, fungible
email: ARRRmada@pirate.black
description: >- 
  The ARRRmada is a link directory for all stores, service providers and companies 
  that accept ARRR as a payment.

# URLs - CHANGE FOR PRODUCTION
baseurl: ""
url: "https://arrrmada.com"
repo: https://github.com/ARRRmada/ARRRmada.com
readme: https://github.com/ARRRmada/ARRRmada.com

# Plugins for SEO
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Sitemap Configuration
sitemap:
  exclude:
    - /404.html
    - /listing_decoder.html
  changefreq: weekly
  priority: 0.8

# Feed Configuration  
feed:
  path: feed.xml
  excerpt_only: false

# SEO Tag Configuration
twitter:
  username: PirateARRRmada
  card: summary_large_image

social:
  name: ARRRmada
  links:
    - https://twitter.com/PirateARRRmada
    - https://piratechain.com/discord
    - https://github.com/ARRRmada/ARRRmada.com

# Performance & SEO
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
